-- Add new South African cities to sa_city enum safely
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Vanderbijlpark') THEN ALTER TYPE sa_city ADD VALUE 'Vanderbijlpark'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Vereeniging') THEN ALTER TYPE sa_city ADD VALUE 'Vereeniging'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Benoni') THEN ALTER TYPE sa_city ADD VALUE 'Benoni'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Boksburg') THEN ALTER TYPE sa_city ADD VALUE 'Boksburg'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Brakpan') THEN ALTER TYPE sa_city ADD VALUE 'Brakpan'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Germiston') THEN ALTER TYPE sa_city ADD VALUE 'Germiston'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Springs') THEN ALTER TYPE sa_city ADD VALUE 'Springs'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Krugersdorp') THEN ALTER TYPE sa_city ADD VALUE 'Krugersdorp'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Randfontein') THEN ALTER TYPE sa_city ADD VALUE 'Randfontein'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Oudtshoorn') THEN ALTER TYPE sa_city ADD VALUE 'Oudtshoorn'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Worcester') THEN ALTER TYPE sa_city ADD VALUE 'Worcester'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Swellendam') THEN ALTER TYPE sa_city ADD VALUE 'Swellendam'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Bellville') THEN ALTER TYPE sa_city ADD VALUE 'Bellville'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Somerset West') THEN ALTER TYPE sa_city ADD VALUE 'Somerset West'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Newcastle') THEN ALTER TYPE sa_city ADD VALUE 'Newcastle'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Empangeni') THEN ALTER TYPE sa_city ADD VALUE 'Empangeni'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Richards Bay') THEN ALTER TYPE sa_city ADD VALUE 'Richards Bay'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Pinetown') THEN ALTER TYPE sa_city ADD VALUE 'Pinetown'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Umlazi') THEN ALTER TYPE sa_city ADD VALUE 'Umlazi'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Mooi River') THEN ALTER TYPE sa_city ADD VALUE 'Mooi River'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Howick') THEN ALTER TYPE sa_city ADD VALUE 'Howick'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Bhisho') THEN ALTER TYPE sa_city ADD VALUE 'Bhisho'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'KuGompo City') THEN ALTER TYPE sa_city ADD VALUE 'KuGompo City'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Kariega') THEN ALTER TYPE sa_city ADD VALUE 'Kariega'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Mthatha') THEN ALTER TYPE sa_city ADD VALUE 'Mthatha'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Makhanda') THEN ALTER TYPE sa_city ADD VALUE 'Makhanda'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Graaff-Reinet') THEN ALTER TYPE sa_city ADD VALUE 'Graaff-Reinet'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Welkom') THEN ALTER TYPE sa_city ADD VALUE 'Welkom'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Odendaalsrus') THEN ALTER TYPE sa_city ADD VALUE 'Odendaalsrus'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Sasolburg') THEN ALTER TYPE sa_city ADD VALUE 'Sasolburg'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Bethlehem') THEN ALTER TYPE sa_city ADD VALUE 'Bethlehem'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Kroonstad') THEN ALTER TYPE sa_city ADD VALUE 'Kroonstad'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Parys') THEN ALTER TYPE sa_city ADD VALUE 'Parys'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Clarens') THEN ALTER TYPE sa_city ADD VALUE 'Clarens'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Musina') THEN ALTER TYPE sa_city ADD VALUE 'Musina'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Phalaborwa') THEN ALTER TYPE sa_city ADD VALUE 'Phalaborwa'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Thabazimbi') THEN ALTER TYPE sa_city ADD VALUE 'Thabazimbi'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Makhado') THEN ALTER TYPE sa_city ADD VALUE 'Makhado'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Bela-Bela') THEN ALTER TYPE sa_city ADD VALUE 'Bela-Bela'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Tzaneen') THEN ALTER TYPE sa_city ADD VALUE 'Tzaneen'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'eMalahleni') THEN ALTER TYPE sa_city ADD VALUE 'eMalahleni'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Middelburg') THEN ALTER TYPE sa_city ADD VALUE 'Middelburg'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Secunda') THEN ALTER TYPE sa_city ADD VALUE 'Secunda'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Ermelo') THEN ALTER TYPE sa_city ADD VALUE 'Ermelo'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Standerton') THEN ALTER TYPE sa_city ADD VALUE 'Standerton'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Barberton') THEN ALTER TYPE sa_city ADD VALUE 'Barberton'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Sabie') THEN ALTER TYPE sa_city ADD VALUE 'Sabie'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Mahikeng') THEN ALTER TYPE sa_city ADD VALUE 'Mahikeng'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Klerksdorp') THEN ALTER TYPE sa_city ADD VALUE 'Klerksdorp'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Brits') THEN ALTER TYPE sa_city ADD VALUE 'Brits'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Hartbeespoort') THEN ALTER TYPE sa_city ADD VALUE 'Hartbeespoort'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Lichtenburg') THEN ALTER TYPE sa_city ADD VALUE 'Lichtenburg'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Vryburg') THEN ALTER TYPE sa_city ADD VALUE 'Vryburg'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Springbok') THEN ALTER TYPE sa_city ADD VALUE 'Springbok'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'De Aar') THEN ALTER TYPE sa_city ADD VALUE 'De Aar'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = 'sa_city'::regtype AND enumlabel = 'Kuruman') THEN ALTER TYPE sa_city ADD VALUE 'Kuruman'; END IF; END $$;
